;/*!relative/main.atom*/
define("wiseatom/relative/main",["require","exports","module","modules/invoke/recInvokeBox","search-ui/v2/Title/Title","search-ui/v2/Row/Row","search-ui/v2/Row/Span","search-ui/v2/Link/Link"],function(t,e,r){var i={exports:{}};!function(t){t.exports={render:function(){var t=this,e=t.$createElement,r=t._self._c||e;return r("div",{staticClass:"se-relativewords","class":{darken:t.darken},attrs:{id:"relativewords"}},[r("c-title",{staticClass:"rw-title",attrs:{text:t.title,icon:"baidu"}}),t.darken?t._e():r("div",{staticClass:"rw-list"},[t._l(t.list,function(e){return[r("c-link",{ref:"$item",refInFor:!0,staticClass:"rw-item",attrs:{url:e.href}},[t._v(t._s(e.text))])]
})],2),t.darken?r("div",{staticClass:"rw-list"},[r("c-row",t._l(t.list,function(e,i){return r("c-span",{key:i,attrs:{col:"6"}},[r("c-link",{staticClass:"rw-item c-line-clamp1",attrs:{url:e.href}},[t._v(t._s(e.text))])],1)}))],1):t._e()],1)},staticRenderFns:[]}}(i,i.exports);var n={exports:{}};!function(e,r){"use strict";Object.defineProperty(r,"__esModule",{value:!0});var i=t("modules/invoke/recInvokeBox");r.default={mounted:function(){this._init()},methods:{_init:function(){var e=this;t(["modules/recmmend/aftclk_rcmd/asyn_rcmd"],function(t){var r;
"[object Array]"===Object.prototype.toString.call(t.getData("toprq"))?r=t.getData("toprq"):"[object Array]"===Object.prototype.toString.call(t.getData("rs"))&&(r=t.getData("rs")),r&&r.length&&e.replace(r),e.invokeShoubai()})},replace:function(t){this.list=t},invokeShoubai:function(){var t=this;i.recInvokeBox({invokeElem:t.$refs.$item,control:t.control,position:10})}}}}(n,n.exports);var a=n.exports.default||n.exports;a.render=a.render||i.exports.render,a.staticRenderFns=i.exports.staticRenderFns,a.data=function(){return{}
},a.props={list:{type:Object},darken:{type:Boolean,"default":!1},title:{type:String,"default":"相关搜索"},control:{type:Object,"default":function(){return{}}}},a.components={"c-title":t("search-ui/v2/Title/Title"),"c-row":t("search-ui/v2/Row/Row"),"c-span":t("search-ui/v2/Row/Span"),"c-link":t("search-ui/v2/Link/Link")};var s=a.created;a.created=function(){var t=this;t.$super={render:function(){return i.exports.render.apply(t,arguments)}},s&&s.call(t)},a._scopeId="data-a-b9783d32",r.exports=a});
;/*!relative/swipe.atom*/
define("wiseatom/relative/swipe",["require","exports","module","search-ui/v2/Title/Title","search-ui/v2/Row/Row","search-ui/v2/Row/Span","search-ui/v2/Link/Link","wiseatom/relative/views/carousel/carousel-frame"],function(t,e,r){var i={exports:{}};!function(t){t.exports={render:function(){var t=this,e=t.$createElement,r=t._self._c||e;return r("div",{staticClass:"se-relativewords","class":{darken:t.darken},attrs:{id:"relativewords"}},[r("c-title",{staticClass:"rw-title",attrs:{text:t.title,icon:"baidu"}}),!t.darken&&t.list&&t.list.length?r("div",{staticClass:"rw-list"},[r("c-carousel-frame",{staticClass:"c-row-tile"},t._l(t.list,function(e,i){return r("div",{key:i,staticClass:"carousel-item"},t._l(e,function(e,s){return r("c-link",{key:i+"-"+s,ref:"link",refInFor:!0,staticClass:"rw-item c-line-clamp1",attrs:{url:e.href}},[t._v(t._s(e.text))])
}))}))],1):t._e(),t.darken&&t.list&&t.list.length?r("div",{staticClass:"rw-list"},[r("c-carousel-frame",{staticClass:"c-row-tile"},t._l(t.list,function(e,i){return r("div",{key:i},[r("c-row",t._l(e,function(e,i){return r("c-span",{key:i,attrs:{col:"6"}},[r("c-link",{staticClass:"rw-item c-line-clamp1",attrs:{url:e.href}},[t._v(t._s(e.text))])],1)}))],1)}))],1):t._e()],1)},staticRenderFns:[]}}(i,i.exports);var s={exports:{}};!function(e,r){"use strict";Object.defineProperty(r,"__esModule",{value:!0}),r.default={mounted:function(){this._init()
},methods:{_init:function(){var e=this;t(["modules/recmmend/aftclk_rcmd/asyn_rcmd"],function(t){var r;"[object Array]"===Object.prototype.toString.call(t.getData("toprq"))?r=t.getData("toprq"):"[object Array]"===Object.prototype.toString.call(t.getData("rs"))&&(r=t.getData("rs")),r&&r.length&&(e.replace(r),e.formatRslist())})},replace:function(){this.list=_list},formatRslist:function(){var t=[];for(var e in this.list)t.push(this.list[e]);t=t.slice(0,Math.floor(t.length/this.pageSize)*this.pageSize);
for(var r=[[]],i=t.length,s=0,a=0;i>a;a++)r[s].push(t[a]),(a+1)%10===0&&(r[++s]=[]);return i%2===0&&r.pop(),r},handlePageScrollItemTouchmove:function(){var t=this;this.isTouching||(this.isTouching=!0,setTimeout(function(){t.clearLinkUrl()}))},handlePageScrollItemTouchend:function(){var t=this;setTimeout(function(){t.isTouching=!1,t.resetLinkUrl()},0)},clearLinkUrl:function(){this.$refs.link.forEach(function(t){t.url||(t.url=t.$el.href),t.$el.href="javascript:;"})},resetLinkUrl:function(){this.$refs.link.forEach(function(t){t.$el.href=t.url
})}}}}(s,s.exports);var a=s.exports.default||s.exports;a.render=a.render||i.exports.render,a.staticRenderFns=i.exports.staticRenderFns,a.data=function(){return{pageSize:10,rowSize:5,isTouching:!1}},a.props={list:{type:Array},darken:{type:Boolean,"default":!1},title:{type:String,"default":"相关搜索"},listCount:{type:Number,"default":0}},a.components={"c-title":t("search-ui/v2/Title/Title"),"c-row":t("search-ui/v2/Row/Row"),"c-span":t("search-ui/v2/Row/Span"),"c-link":t("search-ui/v2/Link/Link"),"c-carousel-frame":t("wiseatom/relative/views/carousel/carousel-frame")};
var n=a.created;a.created=function(){var t=this;t.$super={render:function(){return i.exports.render.apply(t,arguments)}},n&&n.call(t)},a._scopeId="data-a-062c0a3e",r.exports=a});
;/*!relative/views/carousel/carousel-frame.atom*/
define("wiseatom/relative/views/carousel/carousel-frame",["require","exports","module","wiseatom/relative/views/carousel/indicator"],function(t,e,i){var s={exports:{}};!function(t){t.exports={render:function(){var t=this,e=t.$createElement,i=t._self._c||e;return i("section",{ref:"carouselFrame",staticClass:"carousel-frame__46521c92",on:{touchstart:t.handleTouchStart,touchmove:t.handleTouchMove,touchend:t.handleTouchEnd}},[i("div",{ref:"carouselLayout",staticClass:"carousel-layout__7c08b2e7",style:{"-webkit-transform":"translateX("+t.disX+"px) scale(1)",transform:"translateX("+t.disX+"px) scale(1)"}},t._l(t.slotsLength,function(e,s){return i("div",{key:s,staticClass:"carousel-item__610a49c4"},[t._t("carouselItem"+s)],2)
})),i("div",{staticClass:"indicator__93862ae2"},[i("c-indicator",{attrs:{length:t.slotsLength,"cur-index":t.activeIndex}})],1)])},staticRenderFns:[]}}(s,s.exports);var n={exports:{}};!function(t,e){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default={mounted:function(){this.width=this.$refs.carouselFrame.offsetWidth,this.addOrientationListenerMixin()},activated:function(){this.addOrientationListenerMixin()},deactivated:function(){this.removeOrientationListenerMixin()},beforeDestory:function(){this.removeOrientationListenerMixin()
},render:function(){var t=this,e=this.$slots.default;return e&&e.length&&(e.forEach(function(e,i){t.$slots["carouselItem"+i]=e}),this.slotsLength=e.length),this.$super.render()},methods:{addOrientationListenerMixin:function(){this.mediaQueryList=window.matchMedia("(orientation: portrait)"),this.mediaQueryList.addListener(this.mediaQueryOrientationListenerMixin)},removeOrientationListenerMixin:function(){this.mediaQueryList.removeListener(this.mediaQueryOrientationListenerMixin)},mediaQueryOrientationListenerMixin:function(){var t=this;
setTimeout(function(){t.width=t.$refs.carouselFrame.offsetWidth},500)},handleTouchStart:function(t){this.slideProtect||(t=t||event,1===t.changedTouches.length&&(this.touchStartTimestamp=(new Date).getTime(),this.startX=t.touches[0].clientX,this.startY=t.touches[0].clientY))},handleTouchMove:function(t){if(this.slideProtect)return t.cancelable&&t.preventDefault(),t.stopPropagation(),!0;if(t=t||event,1!==t.changedTouches.length)return!0;this.moveX=t.touches[0].clientX,this.moveY=t.touches[0].clientY;
var e=this.moveX-this.startX,i=this.moveY-this.startY;if(this.loopTouchJudgement(e))return!0;var s=this.getDirection(e,i);return(3===s||4===s)&&(t.cancelable&&t.preventDefault(),t.stopPropagation(),this.disX=e-this.activeIndex*this.width),t.stopPropagation(),t.cancelable&&t.preventDefault(),!0},handleTouchEnd:function(t){if(!this.slideProtect&&(t=t||event,1===t.changedTouches.length)){this.touchEndTimestamp=(new Date).getTime(),this.endX=t.changedTouches[0].clientX,this.endY=t.changedTouches[0].clientY;
var e=this.endX-this.startX,i=this.endY-this.startY;if(this.loopTouchJudgement(e))return!0;this.disX=e,this.disY=i,Math.abs(this.disX)>this.minChangeWidth&&(this.disX>0?this.activeIndex-=1:this.activeIndex+=1),this.disX=-this.activeIndex*this.width,this.setSlideProtect();{this.touchEndTimestamp-this.touchStartTimestamp}(0!==e||0!==i)&&(t.stopPropagation(),t.cancelable&&t.preventDefault())}},setSlideProtect:function(){var t=this;this.slideProtectTimeout&&this.clearSlideProtect(),this.slideProtect=!0,this.slideProtectTimeout=setTimeout(function(){t.clearSlideProtect()
},300)},clearSlideProtect:function(){this.slideProtect=!1,this.slideProtectTimeout&&(clearTimeout(this.slideProtectTimeout),this.slideProtectTimeout=null)},loopTouchJudgement:function(t){if(!this.loop){if(0>t&&this.activeIndex+1===this.slotsLength)return!0;if(t>0&&0===this.activeIndex)return!0}return!1},getDirection:function(t,e){var i=0;if(Math.abs(t)<2&&Math.abs(e)<2)return i;var s=this.getAngle(t,e);return s>=-135&&-45>=s?i=1:s>45&&135>s?i=2:s>=135&&180>=s||s>=-180&&-135>s?i=3:s>=-45&&45>=s&&(i=4),i
},getAngle:function(t,e){return 180*Math.atan2(e,t)/Math.PI}}}}(n,n.exports);var r=n.exports.default||n.exports;r.render=r.render||s.exports.render,r.staticRenderFns=s.exports.staticRenderFns,r.data=function(){return{activeIndex:0,slotsLength:0,width:0,minChangeWidth:50,startX:0,startY:0,moveX:0,moveY:0,disX:0,disY:0,slideProtect:!1,slideProtectTimeout:null,fixLoopTimeout:null}},r.props={loop:{type:Boolean,"default":!1},transitionOpts:{type:Object,"default":function(){return{animationTime:300}}}},r.components={"c-indicator":t("wiseatom/relative/views/carousel/indicator")};
var o=r.created;r.created=function(){var t=this;t.$super={render:function(){return s.exports.render.apply(t,arguments)}},this.$style={carouselFrame:"carousel-frame__46521c92",carouselLayout:"carousel-layout__7c08b2e7",carouselItem:"carousel-item__610a49c4",indicator:"indicator__93862ae2"},o&&o.call(t)},i.exports=r});
;/*!relative/views/carousel/indicator.atom*/
define("wiseatom/relative/views/carousel/indicator",["require","exports","module"],function(e,t,r){var n={exports:{}};!function(e){e.exports={render:function(){var e=this,t=e.$createElement,r=e._self._c||t;return r("div",{staticClass:"indicator__bae7ebb6",style:{"padding-top":e.paddingTop,"padding-bottom":e.paddingBottom}},["dot"===e.type?e._l(e.length,function(t,n){return r("span",{key:n,staticClass:"indicator-item__b04a6d5a","class":[e.curIndex===n?e.$style.indicatorItemSelected:""]})}):e._e()],2)
},staticRenderFns:[]}}(n,n.exports);var d={exports:{}};!function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default={mounted:function(){},methods:{}}}(d,d.exports);var i=d.exports.default||d.exports;i.render=i.render||n.exports.render,i.staticRenderFns=n.exports.staticRenderFns,i.data=function(){return{}},i.props={length:{type:Number,"default":0},curIndex:{type:[Number,String],"default":-1},type:{type:String,"default":"dot"},paddingTop:{type:String,"default":".1rem"},paddingBottom:{type:String,"default":".1rem"}},i.components={};
var a=i.created;i.created=function(){var e=this;e.$super={render:function(){return n.exports.render.apply(e,arguments)}},this.$style={indicator:"indicator__bae7ebb6",indicatorItem:"indicator-item__b04a6d5a",indicatorItemSelected:"indicator-item-selected__3f44896d"},a&&a.call(e)},r.exports=i});